In [1]:
!pip install numpy

In [2]:
import numpy as np

In [4]:
years_of_experience = np.array([1,2,3,4,5])
years_of_experience

array([1, 2, 3, 4, 5])

##Basic operation

###1. Addition

In [5]:
years_of_experience_plus_one = years_of_experience + 1
years_of_experience_plus_one

array([2, 3, 4, 5, 6])

###2. Subtraction

In [6]:
years_of_experience_minus_one = years_of_experience - 1
years_of_experience_minus_one

array([0, 1, 2, 3, 4])

###3. Division

In [8]:
years_of_experience_half = years_of_experience / 2
years_of_experience_half

array([0.5, 1. , 1.5, 2. , 2.5])

###4. Multiplication

In [9]:
years_of_experience_double = years_of_experience * 2
years_of_experience_double

array([ 2,  4,  6,  8, 10])

###5. Slicing

In [10]:
second_and_third_jobs_experience = years_of_experience[1:3]
second_and_third_jobs_experience

array([2, 3])

###6. Boolean Indexing

In [11]:
jobs_with_more_than_one_year_exp = years_of_experience[years_of_experience >= 2]
jobs_with_more_than_one_year_exp

array([2, 3, 4, 5])

##Math Operation
Aggregate funct:
- `sum` = sum
- `prod` = product
- `cumsum` = cumulative sum
- `cumprod` = cumulative product  

Mathematical operations:
- `sqrt`
- `exp`
- `log`
- `sin`
- `cos`

In [14]:
import random

salary = [random.randint(100000, 150000) for num in range(10)]
salary

[124986,
 107231,
 113538,
 106504,
 146189,
 141842,
 133795,
 146303,
 147382,
 132137]

In [16]:
salary_array = np.array(salary)
salary_array

array([124986, 107231, 113538, 106504, 146189, 141842, 133795, 146303,
       147382, 132137])

In [17]:
# SUM
total_sum_salaries = np.sum(salary_array)
total_sum_salaries

np.int64(1299907)

In [19]:
# Product
product_salaries = np.prod(salary_array)
product_salaries

np.int64(4345831070771567744)

In [20]:
#CUMSUM
cumulative_sum_salaries = np.cumsum(salary_array)
cumulative_sum_salaries

array([ 124986,  232217,  345755,  452259,  598448,  740290,  874085,
       1020388, 1167770, 1299907])

In [21]:
#CUMPROD
cumulative_prod_salaries = np.cumprod(salary_array)
cumulative_prod_salaries

array([              124986,          13402373766,     1521678712644108,
       -3955827051937886112,  7025815046810334432,  7202775660349552576,
         565577733991382848, -6374698519763738432, -4694821718124230528,
        4345831070771567744])

##Statistic Operation
- `mean`
- `median`
- `var` : variance
- `std` : standard deviation
- `min`
- `max`

In [22]:
# mean
average_salary = np.mean(salary_array)
average_salary

np.float64(129990.7)

In [23]:
# median
median_salary = np.median(salary_array)
median_salary

np.float64(132966.0)

In [24]:
# var
salary_variance = np.var(salary_array)
salary_variance

np.float64(235583336.41)

In [25]:
# std
salary_std_dev = np.std(salary_array)
salary_std_dev

np.float64(15348.724260015879)

In [26]:
# min
min_salary = np.min(salary_array)
min_salary

np.int64(106504)

In [27]:
# max
max_salary = np.max(salary_array)
max_salary

np.int64(147382)

##Missing Value / NaN

In [45]:
salary_with_nan = np.array([100000, np.nan, 200000, 3000000, np.nan])
salary_with_nan

array([ 100000.,      nan,  200000., 3000000.,      nan])

##Replace Value

In [46]:
salary_with_nan[salary_with_nan < 130000] = np.nan
salary_with_nan

array([     nan,      nan,  200000., 3000000.,      nan])

##Where
`np.where(condition, if_true_condition, if_false_condition)`

In [ ]:
salary_array = np.where(salary_array < 120000, 120000, salary_array)
salary_array

##Random Sampling
Generate a random numbers/data or samples.
- `np.random.normal`
> specify argumen:
> - `loc`: this is the mean ( μ ) of the normal (Gaussian) distribution
> - `scale`: this is the std dev of the normal (Gaussian) distribution, representing the dispersion from the mean.
> - `size`: This defines the number of random samples to draw, which is set to match the number of job posting.
> - Syntax: `np.random.normal(loc=0.0, scale=1.0, size=None)`
- `np.random.rand`
- `np.random.randn`
- `np.random.randint`
- `np.random.random`
- `np.random.uniform`
- `np.random.binomial`
- `np.random.poisson`

In [62]:
# Generate numbers based on normal distribution
noise = np.random.normal(0, 5000, 10)
salary_array_with_noise = salary_array + noise
salary_array_with_noise

array([117926.96968367,  98257.63081129, 113838.04431321, 105577.48607533,
       144100.70736124, 146270.34600398, 137654.09852041, 147391.42991205,
       151246.36430535, 131007.47196378])